# -*- coding: utf-8 -*-
"""Assignment 3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qEgTzMGHzOITM596YGvnSFQ7H5A58-Ap
"""

import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

url = 'https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv'
df=pd.read_csv(url)

pd.pivot_table(df, index= 'continent', columns= 'year', values='lifeExp')

df = sn.heatmap(df)